version: '3.7'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.0.0
    environment:
      # The KAFKA_ADVERTISED_LISTENERS variable is set to kafka:9092. This will make Kafka accessible to other
      # containers by advertising it’s location on the Docker network. The same ZooKeeper port is specified here as
      # the previous container.
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # The KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR is set to 1 for a single-node cluster. If you have three or more
      # nodes, you do not need to change this from the default.
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092

  kafka-manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - 9000:9000